### ISSUE TITLE
Run in build file

### ISSUE THREAD

**Issue by ghost** [bilalba/InputArgs#1]
Would it be possible to make inputArgs run only when a certain build system is used?
I often use building as a debugger and not having to press enter every time would be appreciated.

**Comment by bilalba** [comment]
Basically you want the option to disable InputArgs on certain build systems?

**Comment by kriiizzi** [comment]
Yes, but only certain variants, the ones that do not run the program.

**Comment by bilalba** [comment]
What language are you trying to achieve this for? Perhaps one way to achieve this would be to determine through the command being passed whether it's a run command or a build command.

**Comment by kriiizzi** [comment]
I'm working with Python, Java and Have. How would I go about doing as you suggested?

**Comment by YousefH** [comment]
@kriiizzi 

I think an easier way to achieve this is to  manually disable or enable the plugin? I mean for the time being.

**Comment by bilalba** [comment]
Agreed with @YousefH , you can perhaps use package control to disable the plugin, and enable it once again when you want to use it again.
