### ISSUE TITLE
str expected, not dict

### ISSUE THREAD

**Issue by jcrben** [bilalba/InputArgs#2]
Have you seen this message?

I'm trying to use this with C and I keep getting this message. The error is discussed a bit at http://stackoverflow.com/questions/39576975/capturing-errors-in-sublime-build-file-using-regex-in-sublime-text-3

I just want to see the result of the command without error matching...

**Comment by bilalba** [comment]
> Set the following view settings in a results view if you want to enable results navigation

I presume _**'result_file_regex'**_ is an option that you don't set in the build file, rather in sublime's python API. Have a look around github on how other people have used it. Try [this.](https://github.com/search?utf8=%E2%9C%93&q=result_file_regex&type=Code&ref=searchresults)

**Comment by jcrben** [comment]
Line regex will default to an empty string at https://github.com/bilalba/InputArgs/blob/master/exec.py#L134 so it should be able to handle it left unset.

I don't want to enable results navigation. I just want to see the output - so I shouldn't have to set `result_file_regex`.

I'll fiddle with a bit more...

**Comment by jcrben** [comment]
`kwargs` is a dict and assigned to `self.sl` but what is expected is a path.

After fixing that, seems to be another bug affecting how shell_cmd and finding the files. I fixed it real quick by hardcoding a couple variables. Hopefully will make a pull request sometime but this is more a curiosity project for me...

This may have to do with conflicting ideas of how to write build files as well...

**Comment by bilalba** [comment]
I don't clearly understand what you're trying to do. Are you not able to see the output of the program already in the Sublime Text window?

**Comment by jcrben** [comment]
Yeah, the errors need to be fixed for the program to run the command.
