### ISSUE TITLE
Feature Suggestion 

### ISSUE THREAD

**Issue by YousefH** [bilalba/InputArgs#3]
A history, similar to 'find' feature would be useful.

Edit: I found that the plugin [AlignTab](https://github.com/randy3k/AlignTab) has this feature. Specifically this [file](https://github.com/randy3k/AlignTab/blob/master/hist.py).

**Comment by bilalba** [comment]
I myself wanted this. I wasn't sure if this could be implemented in the current Sublime API. Thank you for pointing it out.

**Comment by bilalba** [comment]
Implemented! Do provide feedback on it.
