### ISSUE TITLE
Doesn't work in my sublime text2

### ISSUE THREAD

**Issue by SejoongDeJang** [bilalba/InputArgs#5]
Hello~
I expect this plugin reducing usage of terminal.
My node project is run with command line.
At that time, I wrote code and moved to terminal and typing command such as 'node src.js --list' or 'node model.js --parse'.
But when I installed your package and inputed 'ctrl+b', I had error.

Followed log is occured everytime.

Unable to find target command: exec

My node build is like followed:
{
	"cmd": ["node"],
	"selector": "source.js"
}

Can you help me?

**Comment by bitwise35** [comment]
Hi, I want to echo the problem SejoongDeJang is having. This is working in ST3, but receiving the same  error msg: 'Unable to find target command: exec'
Please let me know if there's anything I can do to help, really looking forward to getting this to work on ST2..

**Comment by bilalba** [comment]
What operating system are you running this on? Is it windows?

**Comment by bitwise35** [comment]
It it running on macOS sierra (10.12.3)

**Comment by bilalba** [comment]
Fixed.

**Comment by bitwise35** [comment]
Thank you SO MUCH! Works perfect!

**Comment by bitwise35** [comment]
Hi again, another small problem. When using, it's passing space separated arguments as one single string :)
