### ISSUE TITLE
Args editor shows when using open recent menu function

### ISSUE THREAD

**Issue by ghost** [bilalba/InputArgs#6]
File->open recent->select any file

**Comment by PalantirWielder** [comment]
This might be a different issue, but I found that in Sublime 3.0 on OSX 10.10.5, when I open a file via the normal "Open" or with the "Recent", the "Input Args" box at the bottom shows up.

**Comment by bilalba** [comment]
Thank you for reporting this issue. This comes with the introduction of [Phantoms](https://forum.sublimetext.com/t/dev-build-3118/21270) in the build system. Working on it to add support for phantoms and fix this issue.

**Comment by bilalba** [comment]
Fixed.
